version: "3"

services:
  api:
    build: .
    command: yarn dev -- -L
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/solysis
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

volumes:
  db:
