version: "3"

services:
  api:
    build: .
    command: yarn start
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://doadmin:2ScTr6418gXH5v03@db-mongodb-fra1-21691-f756f24b.mongo.ondigitalocean.com/admin?authSource=admin&replicaSet=db-mongodb-fra1-21691&tls=true&tlsCAFile=/root/certs/ca-certificate.crt
    ports:
      - "3000:3000"
